spring:
  thymeleaf:
    cache: false
    prefix: ${project.base-dir}/src/main/resources/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/J_DB?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1121
  jwt:
    secret: jwtsecret
  redis:
    port: 6379
    host: 127.0.0.1
  jpa:
    hibernate:
      #옵션 create, update, none, create-drop, validate 있음
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    showSql: true

project:
  base-dir: file:////Users/hyunwoo/Documents/practice/practice

server:
  port: 8080

logging:
  level:
    org:hibernate:SQL: DEBUG
